video_source: /content/drive/MyDrive/1.mp4  # 0 for webcam, or path/URL for video file/stream
detector:
  model: yolov8m  # yolov8n, yolov8s, yolov8m, efficientdet-d0, efficientdet-d1
  confidence_threshold: 0.3
tracker:
  algorithm: botsort  # bytetrack or botsort
  iou_threshold: 0.3
  max_age: 250
  min_confidence: 0.3
visualization:
  display: false
  save_output: true
  output_path: /content/drive/MyDrive/Trans_1.mp4
logging:
  save_tracks: true
  tracks_file: tracks.csv
reid:
  type: transformer
  model: TransReID  # or mgn, pcb_p6, abd_resnet50
  device: cuda
  checkpoint: /path/to/your/transreid_weights.pth