video_source: /content/drive/MyDrive/1.mp4  # 0 for webcam, or path/URL for video file/stream
detector:
  model: yolov8m  # yolov8n, yolov8s, yolov8m, efficientdet-d0, efficientdet-d1
  confidence_threshold: 0.3
tracker:
  algorithm: botsort  # bytetrack or botsort
  iou_threshold: 0.3
  max_age: 30
  min_confidence: 0.3
visualization:
  display: false
  save_output: true
  output_path: /content/drive/MyDrive/output1.mp4
logging:
  save_tracks: true
  tracks_file: tracks.csv
reid:
  type: transformer
  model: vit_small_ics  # (or the model name you want, matching the config .yml)
  device: cuda
  checkpoint: /absolute/path/to/your/transformer_120.pth  # set this to your downloaded TransReID checkpoint
